# Generated by Django 3.0 on 2022-01-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfile',
            name='image',
            field=models.ImageField(upload_to='documents/', verbose_name='元画像'),
        ),
    ]
