# Generated by Django 3.0 on 2022-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0002_auto_20220130_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='right_lv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
