# Generated by Django 3.0 on 2022-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crsapp', '0003_auto_20220131_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfile',
            name='left_lv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='nnbd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='theta1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelfile',
            name='theta2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='right_lv',
            field=models.FloatField(default=0.0, verbose_name='右肩'),
        ),
    ]
